---
deployment:
  tasks:
    - export DEPLOYPATH=/home/akashwco/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R style $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH